[package]
name = "nuui"
version = "0.9.4"
edition = "2024"

[dependencies]
directories = "6.0"
arboard = { version = "3.4", default-features = false }

[target.'cfg(unix)'.dependencies]
libc = "0.2.186"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Console", "Win32_UI_Input_KeyboardAndMouse"] }
