[package]
name = "nuui"
version = "0.12.6"
edition = "2024"

[features]
portable = []

[dependencies]
directories = "6.0"
arboard = { version = "3.4", default-features = false }
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.186"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Console", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_Threading", "Win32_System_SystemInformation", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
