title = ' {1d304a}▄▄▄   {2d5772}▄ {356b86}▄   {40829a}▄ {4f9caa}▄   {5bc0be}▄▄▄
 {1d304a}█ █   {2d5772}█ {356b86}█   {40829a}█ {4f9caa}█    {5bc0be}█
 {1d304a}█ █   {2d5772}█▄{356b86}█   {40829a}█▄{4f9caa}█   {5bc0be}▄█▄ EX'

main_label = 5bc0be
warning_color = e65f5c d0413e
caret_color = e2e8f0

tabs_box = 050811 080d1a
list_box = 080d1a 0c1324
main_box = 0c1324 10192e

settings_category_box = 080d1a 0c1324
settings_options_box = 0c1324 10192e
selected_box = 1d304a 2d5772

list_folder = 4f9caa 5bc0be
list_file = e2e8f0

tab_lazy = 475569
tab_selected = 5bc0be 4f9caa

macro_output = e2e8f0

settings_entry = e2e8f0
settings_selected = 5bc0be 4f9caa
settings_special = bc4749
fancy_bools_true = 5bc0be
fancy_bools_false = bc4749

editor_ins = 00b4d8
editor_cmd = 48cae4
editor_vis = 5bc0be
editor_fnd = 4f9caa
editor_lne = 4f9caa

editor_fnd_bg = e2e8f0 f8fafc
editor_keywords = 2563eb 1d4ed8
editor_functions = 3b82f6
editor_strings = 60a5fa
editor_numbers = 93c5fd
editor_bool = 93c5fd
editor_comments = 1e293b 334155
editor_variables = e2e8f0
editor_operators = 3b82f6
editor_brackets = 94a3b8
editor_errors = ef4444 1e40af

keyview_color = 5bc0be 2d5772

monitor_cpu_key = 356b86 4f9caa
monitor_cpu_val = 4f9caa 5bc0be
monitor_gpu_key = 356b86 4f9caa
monitor_gpu_val = 4f9caa 5bc0be
monitor_mem_key = 356b86 4f9caa
monitor_mem_val = 4f9caa 5bc0be
monitor_term_key = 356b86 4f9caa
monitor_term_val = 4f9caa 5bc0be
monitor_divider = 1d304a
monitor_bar_bounds = 1d304a 0c1324

clock_time_color = 5bc0be 2d5772
clock_date_color = 4f9caa

macrostats_key = 356b86 4f9caa
macrostats_val = 4f9caa 5bc0be
macrostats_err = 38b000 ffb703 ef4444

matrix_head_color = e2e8f0
matrix_body_color = 5bc0be 356b86
