title = ' {3a5a40}█▀█ █ █ {dad7cd}█ █ ▀█▀
 {3a5a40}█ █ █ █ {dad7cd}█ █  █
 {3a5a40}▀ ▀ ▀▀▀ {dad7cd}▀▀▀ ▀▀▀ {3a5a40}ex'

main_label = f4a259

main_box = 344e41
list_box = 3a5a40
tabs_box = 588157
settings_category_box = 3a5a40
settings_options_box = 588157
selected_box = 90a955

list_folder = a3b18a
list_file = dad7cd

settings_entry = dad7cd
settings_selected = f4a259
settings_special = bc4749

editor_cmd = ff7f51
editor_vis = ff9b54
editor_ins = ce4257
