title = ' {0d2b30}▄▄▄   {17454d}▄ {22606b}▄   {2d7a88}▄ {3995a6}▄   {45b0c4}▄▄▄
 {0d2b30}█ █   {17454d}█ {22606b}█   {2d7a88}█ {3995a6}█    {45b0c4}█
 {0d2b30}█ █   {17454d}█▄{22606b}█   {2d7a88}█▄{3995a6}█   {45b0c4}▄█▄ EX'

main_label = 52b788
warning_color = e07a5f c96a53
caret_color = e0f2f1

tabs_box = 03080a 07161a
list_box = 07161a 0f262c
main_box = 0f262c 16363e

settings_category_box = 07161a 0f262c
settings_options_box = 0f262c 16363e
selected_box = 1f4e59 2a6b7a

list_folder = 2ec4b6 52b788
list_file = e0f2f1

tab_lazy = 405d63
tab_selected = 52b788 2ec4b6

macro_output = e0f2f1

settings_entry = e0f2f1
settings_selected = 52b788 2ec4b6
settings_special = e07a5f
fancy_bools_true = 52b788
fancy_bools_false = e07a5f

editor_ins = 1f4e59
editor_cmd = 2a6b7a
editor_vis = 3995a6
editor_fnd = 2ec4b6
editor_lne = 2ec4b6

editor_fnd_bg = e0f2f1 eefaf9
editor_keywords = 52b788 2ec4b6
editor_functions = 72efdd
editor_strings = b5e2fa
editor_numbers = f4f1de
editor_bool = f4f1de
editor_comments = 2d4a50 3c5e66
editor_variables = e0f2f1
editor_operators = 74c69d
editor_brackets = e0f2f1
editor_errors = e07a5f

keyview_color = 2ec4b6 52b788

monitor_cpu_key = 2d7a88 3995a6
monitor_cpu_val = 3995a6 52b788
monitor_gpu_key = 2d7a88 3995a6
monitor_gpu_val = 3995a6 52b788
monitor_mem_key = 2d7a88 3995a6
monitor_mem_val = 3995a6 52b788
monitor_term_key = 2d7a88 3995a6
monitor_term_val = 3995a6 52b788
monitor_divider = 1f4e59
monitor_bar_bounds = 1f4e59 0f262c

clock_time_color = 2ec4b6 52b788
clock_date_color = 3995a6

macrostats_key = 2d7a88 3995a6
macrostats_val = 3995a6 52b788
macrostats_err = 52b788 f4f1de e07a5f
