title = ' {333333}▄▄▄   {666666}▄ {808080}▄   {b3b3b3}▄ {d9d9d9}▄   {ffffff}▄▄▄
 {333333}█ █   {666666}█ {808080}█   {b3b3b3}█ {d9d9d9}█    {ffffff}█
 {333333}█ █   {666666}█▄{808080}█   {b3b3b3}█▄{d9d9d9}█   {ffffff}▄█▄ EX'

main_label = ffffff
warning_color = e0e0e0 a6a6a6
caret_color = ffffff

tabs_box = 0a0a0a 121212
list_box = 121212 1c1c1c
main_box = 1c1c1c 262626

settings_category_box = 121212 1c1c1c
settings_options_box = 1c1c1c 262626
selected_box = 333333 4d4d4d

list_folder = a6a6a6 d9d9d9
list_file = e0e0e0

tab_lazy = 595959
tab_selected = ffffff d9d9d9

macro_output = e0e0e0

settings_entry = e0e0e0
settings_selected = ffffff d9d9d9
settings_special = 8c8c8c
fancy_bools_true = ffffff
fancy_bools_false = 3c3c3c

editor_ins = d9d9d9
editor_cmd = b3b3b3
editor_vis = a6a6a6
editor_fnd = 808080
editor_lne = 808080
editor_trailing_spaces = 595959

editor_fnd_bg = e5e5e5 f5f5f5
editor_keywords = ffffff d9d9d9
editor_functions = e0e0e0
editor_strings = 808080
editor_numbers = ffffff
editor_bool = ffffff
editor_comments = 4d4d4d 595959
editor_variables = e0e0e0
editor_operators = cccccc
editor_brackets = e0e0e0
editor_errors = ffffff 808080

keyview_color = d9d9d9 808080

monitor_cpu_key = 808080 a6a6a6
monitor_cpu_val = a6a6a6 ffffff
monitor_gpu_key = 808080 a6a6a6
monitor_gpu_val = a6a6a6 ffffff
monitor_mem_key = 808080 a6a6a6
monitor_mem_val = a6a6a6 ffffff
monitor_term_key = 808080 a6a6a6
monitor_term_val = a6a6a6 ffffff
monitor_divider = 4d4d4d
monitor_bar_bounds = 333333 1c1c1c

clock_time_color = d9d9d9 808080
clock_date_color = a6a6a6

macrostats_key = 808080 a6a6a6
macrostats_val = a6a6a6 ffffff
macrostats_err = a6a6a6 d9d9d9 ffffff

matrix_head_color = ffffff
matrix_body_color = d9d9d9 808080
