title = ' {Green}▄▄▄   {BrightGreen}▄ {BrightCyan}▄   {Cyan}▄ {BrightBlue}▄   {Blue}▄▄▄
 {Green}█ █   {BrightGreen}█ {BrightCyan}█   {Cyan}█ {BrightBlue}█    {Blue}█
 {Green}█ █   {BrightGreen}█▄{BrightCyan}█   {Cyan}█▄{BrightBlue}█   {Blue}▄█▄ EX'

main_label = Yellow
warning_color = Yellow

tabs_box = BrightBlue
list_box = Blue
main_box = Blue

settings_category_box = BrightBlue
settings_options_box = Blue
selected_box = White

list_folder = Green
list_file = White

tab_lazy = White
tab_selected = Yellow

settings_entry = White
settings_selected = Green
settings_special = Red

editor_ins = Magenta
editor_cmd = Blue
editor_vis = Cyan
editor_src = BrightCyan

editor_src_bg = White
editor_keywords = Magenta
editor_functions = BrightBlue
editor_strings = BrightGreen
editor_numbers = BrightYellow
editor_bool = Cyan
editor_comments = DarkGray
editor_variables = White
editor_operators = BrightCyan
editor_brackets = White
editor_errors = Red

keyview_color = BrightBlue

monitor_cpu_key = Blue
monitor_cpu_val = Magenta
monitor_gpu_key = Blue
monitor_gpu_val = Magenta
monitor_mem_key = Blue
monitor_mem_val = Magenta
monitor_term_key = Blue
monitor_term_val = Magenta
monitor_divider = DarkGray
monitor_bar_bounds = DarkGray

clock_time_color = Green
clock_date_color = Cyan
