title = ' {Green}▄▄▄   {BrightGreen}▄ {BrightCyan}▄   {Cyan}▄ {BrightBlue}▄   {Blue}▄▄▄
 {Green}█ █   {BrightGreen}█ {BrightCyan}█   {Cyan}█ {BrightBlue}█    {Blue}█
 {Green}█ █   {BrightGreen}█▄{BrightCyan}█   {Cyan}█▄{BrightBlue}█   {Blue}▄█▄ EX'

main_label = Yellow
warning_color = Yellow

tabs_box = Cyan
list_box = Blue
main_box = Magenta

settings_category_box = Blue
settings_options_box = Magenta
selected_box = White

list_folder = Green
list_file = White

tab_lazy = White
tab_selected = Yellow

settings_entry = White
settings_selected = Green
settings_special = Red

editor_ins = Magenta
editor_cmd = Blue
editor_vis = Cyan
editor_src = BrightCyan

editor_src_bg = White
editor_keywords = BrightMagenta
editor_functions = BrightBlue
editor_strings = BrightGreen
editor_numbers = BrightYellow
editor_bool = Cyan
editor_comments = DarkGray
editor_variables = White
editor_operators = BrightCyan
editor_brackets = White
editor_errors = Red

keyview_color = Magenta
