title = 'THIS IS THE TITLE'

main_label = Yellow

main_box = Magenta
list_box = Blue
tabs_box = Cyan
settings_category_box = Blue
settings_options_box = Blue
selected_box = FFAABB

list_folder = Blue
list_file = Magenta

settings_entry = DarkGray
settings_selected = Blue
settings_special = Yellow

editor_cmd = Yellow
editor_vis = Yellow
editor_ins = Yellow
