title = '   {588157}▄▄▄  {dad7cd}▄ ▄  {588157}▄ ▄  ▄▄▄
   {588157}█ █  {dad7cd}█ █  {588157}█ █   █
   {588157}█ █  {dad7cd}█▄█  {588157}█▄█  ▄█▄  EX'

main_label = e09f3e
warning_color = e09f3e

main_box = 344e41
list_box = 3a5a40
tabs_box = 588157

settings_category_box = 3a5a40
settings_options_box = 588157
selected_box = a3b18a

list_folder = a3b18a
list_file = f2e9e4

tab_lazy = f2e9e4
tab_selected = e09f3e

settings_entry = dad7cd
settings_selected = e09f3e
settings_special = bc4749

editor_ins = c1121f
editor_cmd = e76f51
editor_vis = f4a261
editor_src = a3b18a

editor_src_bg = e09f3e
editor_keywords = e09f3e
editor_functions = a3b18a
editor_strings = 588157
editor_numbers = dda15e
editor_bool = dda15e
editor_comments = 588157
editor_variables = dad7cd
editor_operators = bc4749
editor_brackets = dad7cd
editor_errors = c1121f
