title = ' {240046}▄▄▄   {3c096c}▄ {5a189a}▄   {7b2cbf}▄ {9d4edd}▄   {c77dff}▄▄▄
 {240046}█ █   {3c096c}█ {5a189a}█   {7b2cbf}█ {9d4edd}█    {c77dff}█
 {240046}█ █   {3c096c}█▄{5a189a}█   {7b2cbf}█▄{9d4edd}█   {c77dff}▄█▄ EX'

main_label = c77dff
warning_color = ff0a54 7b2cbf

tabs_box = 0a0514 110a21
list_box = 110a21 1a0f2e
main_box = 1a0f2e 241542

settings_category_box = 110a21 1a0f2e
settings_options_box = 1a0f2e 241542
selected_box = 3c096c 5a189a

list_folder = 9d4edd c77dff
list_file = e0aaff

tab_lazy = 392759
tab_selected = 00f5d4 c77dff

settings_entry = e0aaff
settings_selected = 00f5d4 c77dff
settings_special = 00f5d4

editor_ins = 00f5d4
editor_cmd = 7b2cbf
editor_vis = c77dff
editor_src = 9d4edd

editor_src_bg = 1a0f2e 241542
editor_keywords = 00f5d4 c77dff
editor_functions = 00f5d4
editor_strings = 7b2cbf
editor_numbers = f3d8ff
editor_bool = f3d8ff
editor_comments = 392759 4c3575
editor_variables = e0aaff
editor_operators = 00f5d4
editor_brackets = e0aaff
editor_errors = ff0a54 7b2cbf

keyview_color = 00f5d4 c77dff 5a189a

monitor_cpu_key = 7b2cbf 9d4edd
monitor_cpu_val = 9d4edd c77dff
monitor_gpu_key = 7b2cbf 9d4edd
monitor_gpu_val = 9d4edd c77dff
monitor_mem_key = 7b2cbf 9d4edd
monitor_mem_val = 9d4edd c77dff
monitor_term_key = 7b2cbf 9d4edd
monitor_term_val = 9d4edd c77dff
monitor_divider = 5a189a
monitor_bar_bounds = 5a189a 241542

clock_time_color = 00f5d4 c77dff
clock_date_color = 9d4edd
