title = ' {4cc9f0}▄▄▄   {4361ee}▄ {3f37c9}▄   {7209b7}▄ {b5179e}▄   {f72585}▄▄▄
 {4cc9f0}█ █   {4361ee}█ {3f37c9}█   {7209b7}█ {b5179e}█    {f72585}█
 {4cc9f0}█ █   {4361ee}█▄{3f37c9}█   {7209b7}█▄{b5179e}█   {f72585}▄█▄ EX'

main_label = f72585
warning_color = ff0000 7209b7

tabs_box = 05050a 0a0a14
list_box = 0a0a14 0f0f1f
main_box = 0f0f1f 141429

settings_category_box = 0a0a14 0f0f1f
settings_options_box = 0f0f1f 141429
selected_box = 3f37c9 7209b7

list_folder = f72585 b5179e
list_file = ffffff

tab_lazy = 2a2a40
tab_selected = 4cc9f0 f72585

settings_entry = ffffff
settings_selected = 4cc9f0 f72585
settings_special = fee440

editor_ins = fee440
editor_cmd = 4361ee
editor_vis = b5179e
editor_src = f72585

editor_src_bg = e0e7ff eef2ff
editor_keywords = f72585 b5179e
editor_functions = 4cc9f0
editor_strings = 4361ee
editor_numbers = fee440
editor_bool = fee440
editor_comments = 2a2a40 3f3f5a
editor_variables = ffffff
editor_operators = 4cc9f0
editor_brackets = ffffff
editor_errors = ff0000 7209b7

keyview_color = 4cc9f0 f72585 fee440

monitor_cpu_key = 7209b7 b5179e
monitor_cpu_val = b5179e f72585
monitor_gpu_key = 7209b7 b5179e
monitor_gpu_val = b5179e f72585
monitor_mem_key = 7209b7 b5179e
monitor_mem_val = b5179e f72585
monitor_term_key = 7209b7 b5179e
monitor_term_val = b5179e f72585
monitor_divider = 3f37c9
monitor_bar_bounds = 3f37c9 141429

clock_time_color = 4cc9f0 f72585
clock_date_color = 4361ee
