title = ' {1d304a}▄▄▄   {2d5772}▄ {356b86}▄   {40829a}▄ {4f9caa}▄   {f4e1b5}▄▄▄
 {1d304a}█ █   {2d5772}█ {356b86}█   {40829a}█ {4f9caa}█    {f4e1b5}█
 {1d304a}█ █   {2d5772}█▄{356b86}█   {40829a}█▄{4f9caa}█   {f4e1b5}▄█▄ EX'

main_label = f4e1b5
warning_color = f4e1b5 d4c39e
caret_color = f8f9fa

tabs_box = 152232 0f1925
list_box = 0f1925 0a1018
main_box = 0a1018 05080c

settings_category_box = 0f1925 0a1018
settings_options_box = 0a1018 05080c
selected_box = 1d304a 2d5772

list_folder = a9d6e5 8dc5d8
list_file = f8f9fa

tab_lazy = 475569
tab_selected = f4e1b5 d4c39e

macro_output = f8f9fa

settings_entry = f8f9fa
settings_selected = f4e1b5 d4c39e
settings_special = bc4749
fancy_bools_true = a9d6e5
fancy_bools_false = bc4749

editor_ins = 0077b6 00b4d8
editor_cmd = 00b4d8 48cae4
editor_vis = 48cae4 a9d6e5
editor_fnd = 48cae4
editor_lne = 48cae4

editor_fnd_bg = e0f2fe f0f9ff
editor_keywords = f4e1b5 d4c39e
editor_functions = 6495ed
editor_strings = a9d6e5
editor_numbers = f4e1b5
editor_bool = f4e1b5
editor_comments = 2d425a 3d5a80
editor_variables = f8f9fa
editor_operators = a9d6e5
editor_brackets = f8f9fa
editor_errors = 48cae4 a9d6e5

keyview_color = f4e1b5 d4c39e

monitor_cpu_key = 40829a 48cae4
monitor_cpu_val = 48cae4 a9d6e5
monitor_gpu_key = 40829a 48cae4
monitor_gpu_val = 48cae4 a9d6e5
monitor_mem_key = 40829a 48cae4
monitor_mem_val = 48cae4 a9d6e5
monitor_term_key = 40829a 48cae4
monitor_term_val = 48cae4 a9d6e5
monitor_divider = 1d304a
monitor_bar_bounds = 1d304a 0a1018

clock_time_color = f4e1b5 d4c39e
clock_date_color = a9d6e5

macrostats_key = 40829a 48cae4
macrostats_val = 48cae4 a9d6e5
macrostats_err = 90e0ef 48cae4 f4e1b5

matrix_head_color = f8f9fa
matrix_body_color = 48cae4 0077b6
