title = '   {1d3557}▄▄▄  {f4e1b5}▄ ▄  {1d3557}▄ ▄  ▄▄▄
   {1d3557}█ █  {f4e1b5}█ █  {1d3557}█ █   █
   {1d3557}█ █  {f4e1b5}█▄█  {1d3557}█▄█  ▄█▄  EX'

main_label = f4e1b5

main_box = 1b263b
list_box = 274c77
tabs_box = 468faf

settings_category_box = 274c77
settings_options_box = 1b263b
selected_box = f4e1b5

list_folder = a9d6e5
list_file = f8f9fa

tab_lazy = f8f9fa
tab_selected = f4e1b5

settings_entry = f8f9fa
settings_selected = f4e1b5
settings_special = bc4749

editor_ins = 0077b6
editor_cmd = 00b4d8
editor_vis = 48cae4

editor_keywords = 00b4d8
editor_functions = 48cae4
editor_strings = a9d6e5
editor_numbers = f4e1b5
editor_bool = f4e1b5
editor_comments = 274c77
editor_variables = f8f9fa
editor_operators = bc4749
editor_brackets = f8f9fa
editor_errors = c1121f
