title = '    {1d3557}▄▄▄  {f4e1b5}▄ ▄  {1d3557}▄ ▄  ▄▄▄
    {1d3557}█ █  {f4e1b5}█ █  {1d3557}█ █   █
    {1d3557}█ █  {f4e1b5}█▄█  {1d3557}█▄█  ▄█▄  EX'

main_label = e9c46a

main_box = 1b263b
list_box = 274c77
tabs_box = 468faf

settings_category_box = 274c77
settings_options_box = 468faf

selected_box = 89c2d9

list_folder = a9d6e5
list_file = f8f9fa

settings_entry = f8f9fa
settings_selected = e9c46a
settings_special = d62828

editor_ins = 0077b6
editor_cmd = 00b4d8
editor_vis = 48cae4
