title = ' {592e3d}▄▄▄   {8c4860}▄ {bf6383}▄   {df8aa7}▄ {f0b4c8}▄   {ffdae5}▄▄▄
 {592e3d}█ █   {8c4860}█ {bf6383}█   {df8aa7}█ {f0b4c8}█    {ffdae5}█
 {592e3d}█ █   {8c4860}█▄{bf6383}█   {df8aa7}█▄{f0b4c8}█   {ffdae5}▄█▄ EX'

main_label = f0b4c8
warning_color = ff1a53 bf6383

tabs_box = 0f0a0c 171013
list_box = 171013 1f151a
main_box = 1f151a 291b22

settings_category_box = 171013 1f151a
settings_options_box = 1f151a 291b22
selected_box = 592e3d 8c4860

list_folder = df8aa7 f0b4c8
list_file = ffe6ec

tab_lazy = 4d333b
tab_selected = f0b4c8 df8aa7

settings_entry = ffe6ec
settings_selected = f0b4c8 df8aa7
settings_special = ff4d79

editor_ins = ff809f
editor_cmd = bf6383
editor_vis = df8aa7
editor_fnd = f0b4c8
editor_lne = f0b4c8

editor_fnd_bg = fce7f3 fdf2f8
editor_keywords = f0b4c8 df8aa7
editor_functions = ff809f
editor_strings = bf6383
editor_numbers = ffdae5
editor_bool = ffdae5
editor_comments = 4d333b 66444f
editor_variables = ffe6ec
editor_operators = ff809f
editor_brackets = ffe6ec
editor_errors = ff1a53 bf6383

keyview_color = f0b4c8 8c4860

monitor_cpu_key = bf6383 df8aa7
monitor_cpu_val = df8aa7 f0b4c8
monitor_gpu_key = bf6383 df8aa7
monitor_gpu_val = df8aa7 f0b4c8
monitor_mem_key = bf6383 df8aa7
monitor_mem_val = df8aa7 f0b4c8
monitor_term_key = bf6383 df8aa7
monitor_term_val = df8aa7 f0b4c8
monitor_divider = 8c4860
monitor_bar_bounds = 8c4860 291b22

clock_time_color = f0b4c8 df8aa7
clock_date_color = df8aa7
