title = ' {5e3008}▄▄▄   {82450d}▄ {a15610}▄   {bf6813}▄ {db7b16}▄   {f59022}▄▄▄
 {5e3008}█ █   {82450d}█ {a15610}█   {bf6813}█ {db7b16}█    {f59022}█
 {5e3008}█ █   {82450d}█▄{a15610}█   {bf6813}█▄{db7b16}█   {f59022}▄█▄ EX'

main_label = f59022
warning_color = db7b16 bf6813

tabs_box = 0c0703 140b05
list_box = 140b05 1c0f08
main_box = 1c0f08 26150a

settings_category_box = 140b05 1c0f08
settings_options_box = 1c0f08 26150a
selected_box = 5e3008 82450d

list_folder = bf6813 db7b16
list_file = ffd29d

tab_lazy = 5c4d43
tab_selected = f59022 db7b16

settings_entry = ffd29d
settings_selected = f59022 db7b16
settings_special = bf6813

editor_ins = 82450d
editor_cmd = a15610
editor_vis = bf6813
editor_fnd = db7b16
editor_lne = db7b16

editor_fnd_bg = ffedd5 fff7ed
editor_keywords = f59022 db7b16
editor_functions = ffd29d
editor_strings = b58450
editor_numbers = ffd29d
editor_bool = ffd29d
editor_comments = 4a3a30 5c473a
editor_variables = ffd29d
editor_operators = bf6813
editor_brackets = ffd29d
editor_errors = d64d18 a13000

keyview_color = f59022 82450d db7b16

monitor_cpu_key = a15610 bf6813
monitor_cpu_val = bf6813 f59022
monitor_gpu_key = a15610 bf6813
monitor_gpu_val = bf6813 f59022
monitor_mem_key = a15610 bf6813
monitor_mem_val = bf6813 f59022
monitor_term_key = a15610 bf6813
monitor_term_val = bf6813 f59022
monitor_divider = 82450d
monitor_bar_bounds = 82450d 1c0f08

clock_time_color = f59022 db7b16
clock_date_color = bf6813
