title = ' {141233}▄▄▄   {2f1c5c}▄ {621d6e}▄   {922a75}▄ {c24d4f}▄   {db724d}▄▄▄
 {141233}█ █   {2f1c5c}█ {621d6e}█   {922a75}█ {c24d4f}█    {db724d}█
 {141233}█ █   {2f1c5c}█▄{621d6e}█   {922a75}█▄{c24d4f}█   {db724d}▄█▄ EX'

main_label = db724d
warning_color = e25f63 c73e4a
caret_color = f2e9e4

tabs_box = 080712 0f0d1e
list_box = 0f0d1e 16132a
main_box = 16132a 201a3b

settings_category_box = 0f0d1e 16132a
settings_options_box = 16132a 201a3b
selected_box = 2f1c5c 4c2a75

list_folder = 922a75 c24d4f
list_file = f2e9e4

tab_lazy = 493d59
tab_selected = db724d c24d4f

macro_output = f2e9e4

settings_entry = f2e9e4
settings_selected = db724d c24d4f
settings_special = c73e4a
fancy_bools_true = a24a95
fancy_bools_false = eb825d

editor_ins = 4c2a75
editor_cmd = 621d6e
editor_vis = 922a75
editor_fnd = c24d4f
editor_lne = c24d4f
editor_trailing_spaces = 922a75

editor_fnd_bg = fce4e4 fdf2f2
editor_keywords = db724d c24d4f
editor_functions = e05075
editor_strings = 922a75
editor_numbers = f3a683
editor_bool = f3a683
editor_comments = 2f2347 3d2f5c
editor_variables = f2e9e4
editor_operators = c73e4a
editor_brackets = f2e9e4
editor_errors = c73e4a 922a75

keyview_color = db724d 922a75

monitor_cpu_key = 922a75 c24d4f
monitor_cpu_val = c24d4f db724d
monitor_gpu_key = 922a75 c24d4f
monitor_gpu_val = c24d4f db724d
monitor_mem_key = 922a75 c24d4f
monitor_mem_val = c24d4f db724d
monitor_term_key = 922a75 c24d4f
monitor_term_val = c24d4f db724d
monitor_divider = 4c2a75
monitor_bar_bounds = 4c2a75 16132a

clock_time_color = db724d 922a75
clock_date_color = c24d4f

macrostats_key = 922a75 c24d4f
macrostats_val = c24d4f db724d
macrostats_err = f3a683 e25f63 c73e4a

matrix_head_color = f2e9e4
matrix_body_color = db724d 922a75
