# nuui config

indicator_style = border
border_style = squared
theme = default
lib_sorting = ascending
tabs_num = 4
deck_mode = none
deck_widget = keyvis

monitor_cpu = pctgraph
monitor_gpu = pctgraph
monitor_mem = pctgraph
monitor_term = on
monitor_divider = hide
monitor_bar_mode = clean
monitor_bar_width = 8
monitor_icons = false

keyvis_width = 2
keyvis_height = 3
keyvis_steps = 1
keyvis_spread = 6
keyvis_force = 0.6
keyvis_gravity = 0.4
keyvis_tension = 0.2
keyvis_base = false

bind_edit_insert = i
bind_edit_visual = v
bind_edit_left = h
bind_edit_right = l
bind_edit_up = k
bind_edit_down = j
bind_edit_word_next = w
bind_edit_word_prev = b
bind_edit_line_start = 1
bind_edit_line_end = 0
bind_edit_select_all = a
bind_edit_file_bounds = g
bind_edit_delete = d
bind_edit_copy = y
bind_edit_paste = p
bind_edit_search = f
bind_edit_undo = u
bind_edit_redo = r
bind_edit_save = s

bind_lib_new_file = c
bind_lib_new_folder = z
bind_lib_edit = e
bind_lib_rename = r
bind_lib_delete = d
bind_lib_move_up = k
bind_lib_move_down = j
