# nuui config

settings_style = right
setting_indicator_choice = modern
setting_indicator_custom = modern
fancy_bools = true
indicator_style = underline
border_style = squared
theme = default
show_caret = false
highlight_trailing_spaces = false
lib_sorting = ascending
tabs_num = 4
lib_width = 24
deck = false
deck_mode = keyvis

keyvis_width = 4
keyvis_height = 3
keyvis_steps = 1
keyvis_spread = 16
keyvis_force = 0.6
keyvis_gravity = 0.4
keyvis_tension = 0.2
keyvis_base = false

matrix_height = 3
matrix_density = 75
matrix_dim_ratio = 35
matrix_speed = 1.0
matrix_direction = down
matrix_min_length = 5
matrix_max_length = 20

monitor_cpu = true
monitor_gpu = true
monitor_mem = true
monitor_term = true
monitor_divider = false
monitor_bar = false
monitor_icons = false
monitor_cpu_style = pctgraph
monitor_gpu_style = pctgraph
monitor_mem_style = pctgraph
monitor_bar_style = background
monitor_bar_width = 8

clock_date = true
clock_date_style = rfc 2822
clock_mode = big
clock_position = right
clock_format = 24h
clock_seconds = true

macrostats_icons = false
macrostats_edit_name = true
macrostats_edit_err = true
macrostats_edit_err_style = chart
macrostats_edit_created = true
macrostats_edit_lines = true
macrostats_edit_code = true
macrostats_run_name = true
macrostats_run_elapsed = true
macrostats_run_cpu = true
macrostats_lib_name = true
macrostats_lib_created = true
macrostats_lib_size = true
macrostats_lib_status = true
macrostats_err_chart_len = 6
macrostats_err_chart_num = true

double_q_exit = false

edit_tab_backspace = true
edit_auto_indent = true
edit_auto_bracket = false
edit_error_highlight = background
bind_edit_insert = i
bind_edit_visual = v
bind_edit_fold = t
bind_edit_left = h
bind_edit_right = l
bind_edit_up = k
bind_edit_down = j
bind_edit_word_next = w
bind_edit_word_prev = b
bind_edit_line_start = 1
bind_edit_line_end = 0
bind_edit_select_all = a
bind_edit_file_bounds = g
bind_edit_delete = d
bind_edit_copy = y
bind_edit_paste = p
bind_edit_search = f
bind_edit_error_jump = e
bind_edit_undo = u
bind_edit_redo = r
bind_edit_save = s

bind_lib_new_file = c
bind_lib_new_folder = z
bind_lib_edit = e
bind_lib_rename = r
bind_lib_delete = d
bind_lib_move_up = k
bind_lib_move_down = j
bind_lib_move_out = h
bind_lib_move_in = l
