# Default nuui config

min_w: 80
min_h: 20

title_s: "
BLAH BLAH NUUI NUUI
SOMETHING HERE
LOREM IPSUM FOR THE RECORD
"

title [
    w: width
    h: 3
    x: 0
    y: 0
    pd: 0
    bd: none
    fg: none
    bg: none
    md: none
]

tabs [
    w: width
    h: 3
    x: 0
    y: 3
    pd: 1
    bd: rounded
    fg: rgb(0, 0, 200)
    bg: none
    md: dim
]

main [
    w: width
    h: height - 6
    x: 0
    y: 6
    pd: 1
    bd: light
    fg: yellow
    bg: none
    md: dim
]
